/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sorveteriajanuaria.apresentacao;

/**
 *
 * @author Késia Correiia
 */
public class AjudaSorveteriaJanuariaForm extends javax.swing.JFrame {

    /**
     * Creates new form AjudaSorveteriaJanuaria
     */
    public AjudaSorveteriaJanuariaForm() {
        initComponents();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblTextoAjuda = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPaginaInicialSuporte = new javax.swing.JMenu();
        mnuImprimir = new javax.swing.JMenu();
        mnuPesquisar = new javax.swing.JMenu();
        mnuPerguntar = new javax.swing.JMenu();
        mnuOpcoes = new javax.swing.JMenu();
        mnuItemSairAjuda = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajuda e Suporte da Sorveteria Januária");

        jScrollPane1.setViewportView(lblTextoAjuda);

        lblPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPesquisar.setText("Pesquisar:");

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/buscar.png"))); // NOI18N

        jMenuBar1.setPreferredSize(new java.awt.Dimension(455, 35));

        mnuPaginaInicialSuporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/house.png"))); // NOI18N
        mnuPaginaInicialSuporte.setText("Página Inicial e Suporte");
        jMenuBar1.add(mnuPaginaInicialSuporte);

        mnuImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/printer.png"))); // NOI18N
        mnuImprimir.setText("Imprimir");
        jMenuBar1.add(mnuImprimir);

        mnuPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/book.png"))); // NOI18N
        mnuPesquisar.setText("Pesquisar");
        jMenuBar1.add(mnuPesquisar);

        mnuPerguntar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/user_comment.png"))); // NOI18N
        mnuPerguntar.setText("Perguntar");
        jMenuBar1.add(mnuPerguntar);

        mnuOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/opções.png"))); // NOI18N
        mnuOpcoes.setText("Opções");

        mnuItemSairAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemSairAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/arrow_undo.png"))); // NOI18N
        mnuItemSairAjuda.setText("Sair da Ajuda");
        mnuItemSairAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairAjudaActionPerformed(evt);
            }
        });
        mnuOpcoes.add(mnuItemSairAjuda);

        jMenuBar1.add(mnuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemSairAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairAjudaActionPerformed

        AjudaSorveteriaJanuariaForm.this.dispose();
        
        
    }//GEN-LAST:event_mnuItemSairAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjudaSorveteriaJanuariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjudaSorveteriaJanuariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjudaSorveteriaJanuariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjudaSorveteriaJanuariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjudaSorveteriaJanuariaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTextoAjuda;
    private javax.swing.JMenu mnuImprimir;
    private javax.swing.JMenuItem mnuItemSairAjuda;
    private javax.swing.JMenu mnuOpcoes;
    private javax.swing.JMenu mnuPaginaInicialSuporte;
    private javax.swing.JMenu mnuPerguntar;
    private javax.swing.JMenu mnuPesquisar;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
