/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sorveteriajanuaria.apresentacao;

import br.com.sorveteriajanuaria.entidade.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;


/**
 *
 * @author Késia Correiia
 */
public final class MenuPrincipalForm extends javax.swing.JFrame {
    Usuario usuario = new Usuario();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalForm() {
        initComponents();
        this.dataHora();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        lblDatas = new javax.swing.JLabel();
        lblHoras = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barraMnuPrincipal = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        mnuItemCadastrarUsuario = new javax.swing.JMenuItem();
        mnuItemPesquisarUsuario = new javax.swing.JMenuItem();
        mnuFornecedores = new javax.swing.JMenu();
        mnuItemCadastroFornecedor = new javax.swing.JMenuItem();
        mnuItemPesquisaFornecedor = new javax.swing.JMenuItem();
        mnuRevendedores = new javax.swing.JMenu();
        mnuItemCadastroRevendedor = new javax.swing.JMenuItem();
        mnuItemPesquisarRevendedor = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenu();
        mnuItemCadastroProdutos = new javax.swing.JMenuItem();
        mnuItemPesquisarProdutos = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenu();
        mnuItemCadastrarPedidos = new javax.swing.JMenuItem();
        mnuItemPesquisarPedidos = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuItemSobre = new javax.swing.JMenuItem();
        mnuUsuarioLogado = new javax.swing.JMenu();
        mnuItemLogoff = new javax.swing.JMenuItem();
        mnuItemSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal - Sorveteria Januária");

        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/date.png"))); // NOI18N

        lblHoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/time.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        barraMnuPrincipal.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        barraMnuPrincipal.setMargin(new java.awt.Insets(2, 2, 2, 2));
        barraMnuPrincipal.setOpaque(false);
        barraMnuPrincipal.setPreferredSize(new java.awt.Dimension(359, 35));
        barraMnuPrincipal.setVerifyInputWhenFocusTarget(false);

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/user_gray.png"))); // NOI18N
        mnuUsuarios.setText("Usuários");
        mnuUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        mnuItemCadastrarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        mnuItemCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/cadastro.png"))); // NOI18N
        mnuItemCadastrarUsuario.setText("Cadastro");
        mnuItemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastrarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuItemCadastrarUsuario);

        mnuItemPesquisarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        mnuItemPesquisarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/buscar.png"))); // NOI18N
        mnuItemPesquisarUsuario.setText("Pesquisar");
        mnuItemPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPesquisarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuItemPesquisarUsuario);

        barraMnuPrincipal.add(mnuUsuarios);

        mnuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/menu_usuario.png"))); // NOI18N
        mnuFornecedores.setText("Fornecedores");
        mnuFornecedores.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        mnuItemCadastroFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mnuItemCadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/cadastro.png"))); // NOI18N
        mnuItemCadastroFornecedor.setText("Cadastro");
        mnuItemCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroFornecedorActionPerformed(evt);
            }
        });
        mnuFornecedores.add(mnuItemCadastroFornecedor);

        mnuItemPesquisaFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        mnuItemPesquisaFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/buscar.png"))); // NOI18N
        mnuItemPesquisaFornecedor.setText("Pesquisar");
        mnuItemPesquisaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPesquisaFornecedorActionPerformed(evt);
            }
        });
        mnuFornecedores.add(mnuItemPesquisaFornecedor);

        barraMnuPrincipal.add(mnuFornecedores);

        mnuRevendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/revendedores.png"))); // NOI18N
        mnuRevendedores.setText("Revendedores");
        mnuRevendedores.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        mnuItemCadastroRevendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        mnuItemCadastroRevendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/cadastro.png"))); // NOI18N
        mnuItemCadastroRevendedor.setText("Cadastro");
        mnuItemCadastroRevendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroRevendedorActionPerformed(evt);
            }
        });
        mnuRevendedores.add(mnuItemCadastroRevendedor);

        mnuItemPesquisarRevendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnuItemPesquisarRevendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/buscar.png"))); // NOI18N
        mnuItemPesquisarRevendedor.setText("Pesquisar");
        mnuItemPesquisarRevendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPesquisarRevendedorActionPerformed(evt);
            }
        });
        mnuRevendedores.add(mnuItemPesquisarRevendedor);

        barraMnuPrincipal.add(mnuRevendedores);

        mnuProdutos.setBorder(null);
        mnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/produto.png"))); // NOI18N
        mnuProdutos.setText("Produtos");
        mnuProdutos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        mnuItemCadastroProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuItemCadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/cadastro.png"))); // NOI18N
        mnuItemCadastroProdutos.setText("Cadastro");
        mnuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroProdutosActionPerformed(evt);
            }
        });
        mnuProdutos.add(mnuItemCadastroProdutos);

        mnuItemPesquisarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnuItemPesquisarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/buscar.png"))); // NOI18N
        mnuItemPesquisarProdutos.setText("Pesquisar");
        mnuItemPesquisarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPesquisarProdutosActionPerformed(evt);
            }
        });
        mnuProdutos.add(mnuItemPesquisarProdutos);

        barraMnuPrincipal.add(mnuProdutos);

        mnuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/pedidos.png"))); // NOI18N
        mnuPedidos.setText("Vendas");
        mnuPedidos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        mnuItemCadastrarPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnuItemCadastrarPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/cadastro.png"))); // NOI18N
        mnuItemCadastrarPedidos.setText("Cadastro");
        mnuItemCadastrarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastrarPedidosActionPerformed(evt);
            }
        });
        mnuPedidos.add(mnuItemCadastrarPedidos);

        mnuItemPesquisarPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        mnuItemPesquisarPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/buscar.png"))); // NOI18N
        mnuItemPesquisarPedidos.setText("Pesquisar");
        mnuItemPesquisarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPesquisarPedidosActionPerformed(evt);
            }
        });
        mnuPedidos.add(mnuItemPesquisarPedidos);

        barraMnuPrincipal.add(mnuPedidos);

        mnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/help.png"))); // NOI18N
        mnuAjuda.setText("Ajuda");
        mnuAjuda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        mnuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/information.png"))); // NOI18N
        mnuItemSobre.setText("Sobre");
        mnuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuItemSobre);

        barraMnuPrincipal.add(mnuAjuda);

        mnuUsuarioLogado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/usuario_pequeno.png"))); // NOI18N
        mnuUsuarioLogado.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        mnuItemLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_MASK));
        mnuItemLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/arrow_undo.png"))); // NOI18N
        mnuItemLogoff.setText("Logoff");
        mnuItemLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogoffActionPerformed(evt);
            }
        });
        mnuUsuarioLogado.add(mnuItemLogoff);

        mnuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteriajanuaria/apresentacao/icones/sair.png"))); // NOI18N
        mnuItemSair.setText("Sair");
        mnuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairActionPerformed(evt);
            }
        });
        mnuUsuarioLogado.add(mnuItemSair);

        barraMnuPrincipal.add(mnuUsuarioLogado);

        setJMenuBar(barraMnuPrincipal);
        barraMnuPrincipal.getAccessibleContext().setAccessibleName("MenuP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemCadastrarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastrarPedidosActionPerformed
        // TODO add your handling code here:
         CadastroVendaForm cadastroPedidos = new CadastroVendaForm();
         cadastroPedidos.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastrarPedidosActionPerformed

    private void mnuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroProdutosActionPerformed
        // TODO add your handling code here:
        CadastroProdutosForm cadastroProdutos= new CadastroProdutosForm();
        cadastroProdutos.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroProdutosActionPerformed

    private void mnuItemCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroFornecedorActionPerformed
        // TODO add your handling code here:
        CadastroFornecedoresForm cadastroFornecedores = new CadastroFornecedoresForm();
        cadastroFornecedores.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroFornecedorActionPerformed

    private void mnuItemCadastroRevendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroRevendedorActionPerformed
        // TODO add your handling code here:
        CadastroRevendedoresForm cadastroRevendedores = new CadastroRevendedoresForm();
        cadastroRevendedores.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroRevendedorActionPerformed

    private void mnuItemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        CadastroUsuarioForm cadastroUsuario = new CadastroUsuarioForm();
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastrarUsuarioActionPerformed
                                              

    private void mnuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairActionPerformed
        // TODO add your handling code here:
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Sair do Sistema?","ATENÇÃO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mnuItemSairActionPerformed

    private void mnuItemPesquisarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPesquisarProdutosActionPerformed
        // TODO add your handling code here:
        PesquisaProdutosForm pesquisaProdutos = new PesquisaProdutosForm();
        pesquisaProdutos.setVisible(true);
    }//GEN-LAST:event_mnuItemPesquisarProdutosActionPerformed

    private void mnuItemPesquisaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPesquisaFornecedorActionPerformed
        // TODO add your handling code here:
        PesquisaFornecedoresForm pesquisaFornecedores = new PesquisaFornecedoresForm();
        pesquisaFornecedores.setVisible(true);
    }//GEN-LAST:event_mnuItemPesquisaFornecedorActionPerformed

    private void mnuItemPesquisarRevendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPesquisarRevendedorActionPerformed
        // TODO add your handling code here:
        PesquisaRevendedoresForm pesquisaRevendedor = new PesquisaRevendedoresForm();
        pesquisaRevendedor.setVisible(true);
    }//GEN-LAST:event_mnuItemPesquisarRevendedorActionPerformed

    private void mnuItemPesquisarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPesquisarPedidosActionPerformed
        // TODO add your handling code here:
        PesquisaVendasForm pesquisaPedido = new PesquisaVendasForm();
        pesquisaPedido.setVisible(true);
    }//GEN-LAST:event_mnuItemPesquisarPedidosActionPerformed

    private void mnuItemPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPesquisarUsuarioActionPerformed
        // TODO add your handling code here:
        PesquisaUsuarioForm pesquisaUsuario = new PesquisaUsuarioForm();
        pesquisaUsuario.setVisible(true);
    }//GEN-LAST:event_mnuItemPesquisarUsuarioActionPerformed

    private void mnuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSobreActionPerformed
        // TODO add your handling code here:
        AjudaSorveteriaJanuariaForm ajudaSorveteriaJanuaria = new AjudaSorveteriaJanuariaForm();
        ajudaSorveteriaJanuaria.setVisible(true);
    }//GEN-LAST:event_mnuItemSobreActionPerformed

    private void mnuItemLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogoffActionPerformed
        // TODO add your handling code here:
        this.logoff();
    }//GEN-LAST:event_mnuItemLogoffActionPerformed

    private void logoff(){
        this.dispose();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }
    
    public void dataHora() {
        Date DataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(formato.format(DataSistema));
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }

    class hora implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMnuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDatas;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuFornecedores;
    private javax.swing.JMenuItem mnuItemCadastrarPedidos;
    private javax.swing.JMenuItem mnuItemCadastrarUsuario;
    private javax.swing.JMenuItem mnuItemCadastroFornecedor;
    private javax.swing.JMenuItem mnuItemCadastroProdutos;
    private javax.swing.JMenuItem mnuItemCadastroRevendedor;
    private javax.swing.JMenuItem mnuItemLogoff;
    private javax.swing.JMenuItem mnuItemPesquisaFornecedor;
    private javax.swing.JMenuItem mnuItemPesquisarPedidos;
    private javax.swing.JMenuItem mnuItemPesquisarProdutos;
    private javax.swing.JMenuItem mnuItemPesquisarRevendedor;
    private javax.swing.JMenuItem mnuItemPesquisarUsuario;
    private javax.swing.JMenuItem mnuItemSair;
    private javax.swing.JMenuItem mnuItemSobre;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JMenu mnuProdutos;
    private javax.swing.JMenu mnuRevendedores;
    private javax.swing.JMenu mnuUsuarioLogado;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
